### ISSUE TITLE
[JOSS] Reproducibility - benchmarks do not conform to community standards for dependency management

### ISSUE THREAD

**Issue by aholmes** [pyccel/pyccel-benchmarks#3]
Regarding openjournals/joss-reviews#4991 - This repository is mentioned in the paper being reviewed under "Benchmarks." Upon cloning this repository and following the README.md to run the run_benchmark.py script, I receive errors about missing dependencies.

```sh
$ python run_benchmark.py --verbose --no_pythran --no_pyccel_f --no_pyccel_c
===========================================
    Ackermann
===========================================
-------------------
    python
-------------------
['python3', '-m', 'timeit', '-s', 'from ackermann_mod import ackermann;import sys; sys.setrecursionlimit(3000);', 'ackermann(3,8)']
1 loop, best of 5: 322 msec per loop

-------------------
    numba
-------------------
['python3', '-c', 'from numba_ackermann_mod import ackermann;import sys; sys.setrecursionlimit(3000);import time; t0 = time.process_time(); ackermann(3,8); t1 = time.process_time(); ackermann(3,8); t2 = time.process_time(); print(2*t1-t0-t2)']
Execution Error!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aaron/pyccel-benchmarks/tmp/ackermann/numba_ackermann_mod.py", line 8, in <module>
    from numba import njit
ModuleNotFoundError: No module named 'numba'

['python3', '-m', 'timeit', '-s', 'from numba_ackermann_mod import ackermann;import sys; sys.setrecursionlimit(3000);', 'ackermann(3,8)']
Execution Error!
Traceback (most recent call last):
  File "/usr/lib/python3.9/timeit.py", line 325, in main
    number, _ = t.autorange(callback)
  File "/usr/lib/python3.9/timeit.py", line 223, in autorange
    time_taken = self.timeit(number)
  File "/usr/lib/python3.9/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 3, in inner
    from numba_ackermann_mod import ackermann;import sys; sys.setrecursionlimit(3000);
  File "/home/aaron/pyccel-benchmarks/tmp/ackermann/./numba_ackermann_mod.py", line 8, in <module>
    from numba import njit
ModuleNotFoundError: No module named 'numba'

Ackermann                 | -                         | -
Ackermann (ms)            | 322.00                    | -                         | -
===========================================
    Bellman Ford
===========================================
-------------------
    python
-------------------
['python3', '-m', 'timeit', '-s', 'from bellman_ford_mod import bellman_ford_test;', 'bellman_ford_test()']
Execution Error!
Traceback (most recent call last):
  File "/usr/lib/python3.9/timeit.py", line 325, in main
    number, _ = t.autorange(callback)
  File "/usr/lib/python3.9/timeit.py", line 223, in autorange
    time_taken = self.timeit(number)
  File "/usr/lib/python3.9/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
    bellman_ford_test()
  File "/home/aaron/pyccel-benchmarks/tmp/bellman_ford_test/./bellman_ford_mod.py", line 54, in bellman_ford_test
    from numpy import array
ModuleNotFoundError: No module named 'numpy'

-------------------
    numba
-------------------
['python3', '-c', 'from numba_bellman_ford_mod import bellman_ford_test;import time; t0 = time.process_time(); bellman_ford_test(); t1 = time.process_time(); bellman_ford_test(); t2 = time.process_time(); print(2*t1-t0-t2)']
Execution Error!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aaron/pyccel-benchmarks/tmp/bellman_ford_test/numba_bellman_ford_mod.py", line 8, in <module>
    from numpy import array
ModuleNotFoundError: No module named 'numpy'

['python3', '-m', 'timeit', '-s', 'from numba_bellman_ford_mod import bellman_ford_test;', 'bellman_ford_test()']
Execution Error!
Traceback (most recent call last):
  File "/usr/lib/python3.9/timeit.py", line 325, in main
    number, _ = t.autorange(callback)
  File "/usr/lib/python3.9/timeit.py", line 223, in autorange
    time_taken = self.timeit(number)
  File "/usr/lib/python3.9/timeit.py", line 177, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 3, in inner
    from numba_bellman_ford_mod import bellman_ford_test;
  File "/home/aaron/pyccel-benchmarks/tmp/bellman_ford_test/./numba_bellman_ford_mod.py", line 8, in <module>
    from numpy import array
ModuleNotFoundError: No module named 'numpy'

Bellman Ford              | -                         | -
Traceback (most recent call last):
  File "/home/aaron/pyccel-benchmarks/run_benchmark.py", line 339, in <module>
    unit_index = round(sum(used_units)/len(used_units))
ZeroDivisionError: division by zero
```

**Note**: I explicitly disabled the Pythran and Pyccel benchmarks, or I get the error described in #2.

This repository should include a setup.cfg and setup.py file to conform to the setuptools standards for package distribution. While this repository is not a distributed package in itself, it is currently not possible to reproduce the results described in the paper, and the instructions in README.md are insufficient to run the benchmarks. Conforming to the setuptools standard will allow others to reproduce the benchmark with a single command to install dependencies.

Environment information:

```sh
$ python --version
Python 3.9.9

$ lsb_release -a
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.4
Codename:       kali-rolling

$ uname -a
Linux AARON-XPS 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux
```

**Comment by yguclu** [comment]
@aholmes Thanks for your suggestion! Clearly we have not thought about packaging this repository properly. We are looking into this issue now
